### ISSUE TITLE
🎯1차시 도전 과제

### ISSUE THREAD

**Issue by sohyundoh** [GO-SOPT-SERVER/DohSoHyun#5]
### Tasks
- [x] 클래스 생성 : 여러 접근 제어자 사용, 오버로딩
- [ ] 추상 클래스 상속 
- [x] 인터페이스 상속 : 오버라이딩
- [x] 기본 클래스 상속
- [x] 패키지 구분 후 접근 제어자 사용
- [x] 인스턴스 생성
- [x] 제네릭 사용
